### ISSUE TITLE
TypeError: Expected `trainable` argument to be a boolean, but got: 2

### ISSUE THREAD

**Issue by SalahNouari** [komo135/trade-rl#2]

**Comment by komo135** [comment]
Please explain in detail.

**Comment by SalahNouari** [comment]
2022-03-08 11:00:32.359850: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Traceback (most recent call last):
  File "C:\Users\Home\Desktop\HFT\trade-rl-main\app.py", line 6, in <module>
    agent = traderl.agent.DQN(df=csv_url, model_name="efficientnet_b0", lr=1e-4, pip_scale=25, n=3, use_device="tpu",
  File "C:\Users\Home\Desktop\HFT\trade-rl-main\traderl\agent\dqn.py", line 67, in __init__
    self.model, self.target_model = self.build_model()
  File "C:\Users\Home\Desktop\HFT\trade-rl-main\traderl\agent\dqn.py", line 115, in build_model
    model = self._build_model()
  File "C:\Users\Home\Desktop\HFT\trade-rl-main\traderl\agent\dqn.py", line 103, in _build_model
    model = nn.build_model(self.model_name, self.x.shape[1:], 2, None, self.agent_name)
  File "C:\Users\Home\Desktop\HFT\trade-rl-main\traderl\nn\build_model.py", line 200, in build_model
    model = model.build_model(input_shape, output_size, output_activation, agent)
  File "C:\Users\Home\Desktop\HFT\trade-rl-main\traderl\nn\build_model.py", line 145, in build_model
    x = output_dict[agent](output_size, output_activation, noise, self.noise_ratio[2])(x)
  File "C:\Users\Home\Desktop\HFT\trade-rl-main\traderl\nn\layers\core.py", line 39, in __init__
    super(Output, self).__init__(output_size, activation, noise, noise_r)
  File "C:\Users\Home\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\tensorflow\python\training\tracking\base.py", line 629, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "C:\Users\Home\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\keras\engine\base_layer.py", line 349, in __init__
    raise TypeError(
TypeError: Expected `trainable` argument to be a boolean, but got: 2

**Comment by komo135** [comment]
error:
```python
super(Output, self).__init__(output_size, activation, noise, noise_r)
```
revision:
```python
super(DQNoutput, self).__init__(output_size, activation, noise, noise_r)
```
