### ISSUE TITLE
NameError: name 'self' is not defined

### ISSUE THREAD

**Issue by tomkelon** [komo135/trade-rl#3]

**Comment by komo135** [comment]
Error details please.

**Comment by tomkelon** [comment]
Traceback (most recent call last):
  File "C:\Users\Tomk Vu\Desktop\trade-rl\run.py", line 25, in <module>
    agent.build_model()
  File "C:\Users\Tomk Vu\Desktop\trade-rl\traderl\agent\dqn.py", line 115, in build_model     
    model = self._build_model()
  File "C:\Users\Tomk Vu\Desktop\trade-rl\run.py", line 15, in custom_model
    inputs, x = nn.layers.inputs_f(self.x.shape[1:], dim, 5, 1, False, "same", noise, noise_r)
NameError: name 'self' is not defined
